version: '3.9'

services:
  3c-ai:
    image: ahmedmohammed10/3c-ai:latest
    container_name: 3c-ai
    ports:
      - "7001:7001"
    env_file:
      - .env
    depends_on:
      - mongo
      - qdrant
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 7001

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=zedny123
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  qdrant_data:
