version: '3.9'

services:
  3c:
    build: .
    container_name: 3c
    ports:
      - "7001:7001"
    env_file:
      - .env
    depends_on:
      - mongo
      - qdrant
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    # No command override needed; Dockerfile CMD will run uvicorn main:app

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  qdrant_data:
