name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_REPO }}:latest

    - name: SSH and deploy on remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /mnt/3c/docker-compose
          sudo docker pull ${{ secrets.DOCKER_REPO }}:latest
          sudo docker compose down
          sudo docker compose up -d --build